spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  server:
    port: 8585
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

