spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: car-service-route
          uri: lb://car-service
          predicates:
              - Path=/api/cars/**
          filters:
              - StripPrefix=0
        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=0
        - id: washer-service-route
          uri: lb://washer-service
          predicates:
            - Path=/api/washer/**
          filters:
            - StripPrefix=0
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  server:
    port: 8585
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

